# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.18-cli-node-browsers
        environment:
          #MYSQL_HOST: 127.0.0.1
          #MYSQL_DB: test
          #MYSQL_USER: root
          #MYSQL_ALLOW_EMPTY_PASSWORD: true
          #MYSQL_PASSWORD:
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: ''
      - image: circleci/mysql:5.7.22-ram
        command: mysqld
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repository

    steps:
      - checkout

      # Download and cache dependencies (PHP + JS)
      - restore_cache:
          keys:
          - v1-dependencies-php-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-php-

      - restore_cache:
          keys:
          - v1-dependencies-js-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-js-

      - run:
          name: Installing OS dependencies
          command: sudo apt install mysql-client libpng-dev -y && sudo docker-php-ext-install pdo_mysql
      - run:
          name: Installing PHP dependencies (Composer)
          command: composer install -n --prefer-dist
      - run:
          name: Installing JS dependencies (npm)
          command: npm install
      - run:
          name: Database - create
          command: mysql -h 127.0.0.1 -u root -e "create database test;"
      - run:
          name: "Migrations"
          command: php artisan migrate --force

      - save_cache:
          key: v1-dependencies-php-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - save_cache:
          key: v1-dependencies-js-{{ checksum "package.json" }}
          paths:
            - ./node_modules


      # run tests!
      #- run: phpunit
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER_STAGING@$SSH_HOST_STAGING "uname -a"
